// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import path from "node:path";
import { defineConfig } from "prisma/config";
import { PrismaLibSql } from "@prisma/adapter-libsql";

// Load .env.local manually since dotenv only loads .env
import { config } from "dotenv";
config({ path: path.resolve(process.cwd(), ".env.local"), override: true });

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env.DATABASE_URL ?? "file:./prisma/dev.db",
  },
  migrate: {
    async adapter() {
      return new PrismaLibSql({
        url: process.env.DATABASE_URL ?? "file:./prisma/dev.db",
        authToken: process.env.TURSO_AUTH_TOKEN,
      });
    },
  },
});
